# Generated by Django 3.1.5 on 2021-03-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210306_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FR', 'Sutures'), ('LA', 'Labware'), ('EQ', 'Equipment'), ('IN', 'Instruments'), ('CU', 'Culture'), ('ME', 'Media')], default='LA', max_length=2),
        ),
    ]
