# Generated by Django 3.1.5 on 2021-03-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SU', 'Sutures'), ('LA', 'Labware'), ('EQ', 'Equipment'), ('IN', 'Instruments'), ('CU', 'Culture'), ('ME', 'Media')], default='LA', max_length=2),
        ),
    ]
